baseURL = 'https://cegepmv.github.io/420-411-Interfaces-Humain-Machine/'
languageCode = 'fr-ca'
title = 'Interfaces Humain machine'
theme = 'relearn'
enableEmoji = true


[params]  
  additionalCSS = ["css/custom.css"]
  disableInlineCopyToClipBoard = true


  [[params.themeVariant]]
    auto = []
    identifier = 'relearn-auto'
    name = 'Relearn Light/Dark'

  [[params.themeVariant]]
    identifier = 'zen-light'

  [[params.themeVariant]]
    identifier = 'zen-dark'

  [[params.themeVariant]]
    identifier = 'neon'

  [[params.themeVariant]]
    identifier = 'learn'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false
    style = "dracula"  # or any theme you like

[caches]
  [caches.images]
    dir = ':cacheDir/images'


  
